### ISSUE TITLE
How can I make a dev-environment available with a single command?

### ISSUE THREAD

**Issue by appie2go** [kuberise/kuberise.io#62]
Hi Mojtaba

Thanks for your work. Kuberise is really a great platform! Keep it up!

However, maybe you can help me with the following. I have a repostory at https://github.com/oidcproxydotnet/OidcProxy.Net.Dev which i want to use to provide a development environment for whoever wants to contribute to the OidcProxy.Net project. But it's a lot of work to explain how to initially start the Kuberise platform. Hence my question: Would it be able to provide a simple, memorable way to Set up kuberise initially?

I notice there's some troubleshooting to do in the following situations:

- What if i don't have minikube or kind? Is it possible to warn the user and tell him/her to go get it?
- Is it possible to automate starting the cluster?
- Is it possible to have an indication that the cluster is running successfully and if not to get the logs in one go?

Looking forward to your response,

Thanks again!

Albert

**Comment by mojtabaimani** [comment]
Thanks for the questions. Please follow the onprem instructions from docs here: 

https://kuberise.io/docs/deployment/onprem
